(function () {
  'use strict';
  const STORAGE_KEY = 'ikigai-make-a-life-v1';
  const labels = { love: 'Love', strength: 'Strength', opportunity: 'Opportunity', need: 'Need' };
  const descriptions = { love: 'What pulls you in', strength: 'What you can do well', opportunity: 'What people pay for', need: 'What the world needs' };
  const app = document.getElementById('app');
  let state = load() || { screen: 'home' };

  function uid(prefix) { return prefix + '-' + Math.random().toString(36).slice(2, 9); }
  function esc(value) { return String(value || '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
  function load() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY)); } catch { return null; } }
  function save() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
  function shuffle(array) { const copy = array.slice(); for (let i = copy.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [copy[i], copy[j]] = [copy[j], copy[i]]; } return copy; }
  function cardById(id) { return state.cards.find(card => card.id === id); }
  function player(id) { return state.players.find(p => p.id === id); }
  function activePlayer() { return state.players[state.activeIndex]; }
  function roundPlayers() { const ids=state.roundPlayerIds || state.players.map(p=>p.id); return ids.map(player).filter(Boolean); }
  function round() { return state.round; }
  function header(note = '') { return `<div class="shell"><header class="topbar"><button class="brand" data-action="home"><span class="brand-mark">i</span>ikigai</button><div class="nav-actions"><span class="nav-note">${esc(note)}</span>${state.players ? '<button class="button reset-button" data-action="reset-game">Reset game</button>' : ''}</div></header>`; }
  function close() { return '</div>'; }
  function toast(message) { const node = document.createElement('div'); node.className = 'toast'; node.textContent = message; document.body.append(node); setTimeout(() => node.remove(), 2200); }
  function categoryCard(card, selectable, isSelected) { return `<button class="activity-card ${card.category} ${isSelected ? 'selected' : ''}" data-card="${card.id}" ${selectable ? '' : 'disabled'}><span class="card-dot"></span><span class="category">${labels[card.category]}</span><span class="title">${esc(card.title)}</span></button>`; }
  function selectedPromptCards(ids) { return ids.map(id => { const card = cardById(id); return `<span class="prompt-card ${card.category}"><i></i>${esc(card.title)}</span>`; }).join(''); }
  function progress(current, total) { return `<div class="progress">${Array.from({length:total},(_, i) => `<span class="${i < current ? 'done' : i === current ? 'current' : ''}"></span>`).join('')}</div>`; }

  function renderHome() {
    app.innerHTML = header('a gentle game for imagining work') + `<section class="hero"><div class="hero-copy"><div><div class="eyebrow">make a life with your friends</div><h1>What could your work become?</h1><p class="lead">Draft the ingredients that feel most like you. Then let your friends imagine real, surprising paths forward—together.</p><div class="actions"><button class="button coral" data-action="setup">Start a table</button>${state.players ? `<button class="button quiet" data-action="resume">Resume saved table</button>` : ''}</div></div><aside class="hero-aside"><strong>3–8 friends · 45–90 minutes</strong>Go practical, go strange, or go both. Offer a possibility—not a prescription.</aside></div><div class="category-strip"><div class="love"><span>01</span><b>Love</b><small>What pulls you in</small></div><div class="strength"><span>02</span><b>Strength</b><small>What you can do well</small></div><div class="opportunity"><span>03</span><b>Opportunity</b><small>What people pay for</small></div><div class="need"><span>04</span><b>Need</b><small>What the world needs</small></div></div></section>` + close();
  }
  function renderSetup() {
    app.innerHTML = header('set the table') + `<section class="screen-head"><div class="eyebrow">new game</div><h2>Gather your curious people.</h2><p class="lead">Choose everyone at the table, then choose who gets a spotlight round. Everyone can contribute ideas; only spotlight players receive a personal round.</p></section><section class="panel"><label class="field-label" for="table-name">What should we call this gathering?</label><input id="table-name" type="text" maxlength="48" value="Career Possibilities" placeholder="e.g. Sunday dinner ideas" /><label class="field-label">Players and spotlight rounds</label><div id="player-inputs">${['Ari','Sam','Riley','Jordan'].map((name, i) => playerInput(name, i)).join('')}</div><div class="actions"><button class="button quiet small" data-action="add-player">+ Add a friend</button></div><div class="form-foot"><p class="helper">2–8 people can play. A checked player gets a spotlight round and casts the single vote in that round.</p><button class="button primary" data-action="start-game">Begin drafting →</button></div></section>` + close();
  }
  function playerInput(name, index) { return `<div class="player-entry"><input class="player-name" type="text" maxlength="24" value="${esc(name)}" placeholder="Friend ${index + 1}" /><label class="round-toggle"><input class="round-player" type="checkbox" checked /><span>Spotlight round</span></label><button class="icon-button remove-player" aria-label="Remove player">×</button></div>`; }
  function buildCards() { return Object.entries(window.CARD_LIBRARY).flatMap(([category, titles]) => titles.map((title, index) => ({ id: `${category}-${index + 1}`, category, title }))); }
  function startGame() {
    const entries = [...document.querySelectorAll('.player-entry')].map(entry => ({ name:entry.querySelector('.player-name').value.trim(), playsRound:entry.querySelector('.round-player').checked })).filter(entry => entry.name);
    const names = entries.map(entry => entry.name);
    if (names.length < 2) return toast('Add at least two people to begin.');
    if (new Set(names.map(n => n.toLowerCase())).size !== names.length) return toast('Give each person a distinct name.');
    const cards = buildCards();
    if (cards.length < 32) return toast('The card library is still loading—try again in a moment.');
    const players = names.map(name => ({ id: uid('p'), name, draft: [], keep: [], bank: [] }));
    const roundPlayerIds = players.filter((_, index) => entries[index].playsRound).map(p => p.id);
    if (!roundPlayerIds.length) return toast('Choose at least one player for a spotlight round.');
    const pool = shuffle(cards);
    const hands = players.map((_, index) => pool.slice(index * 8, index * 8 + 8).map(card => card.id));
    state = { screen:'draft', title:document.getElementById('table-name').value.trim() || 'Career Possibilities', roomCode:Math.random().toString(36).slice(2,7).toUpperCase(), players, roundPlayerIds, cards, draft:{ hands, pickRound:0, pickerIndex:0 }, activeIndex:players.findIndex(p => p.id === roundPlayerIds[0]), completedRounds:0 };
    save(); render();
  }
  function renderDraft() {
    const draft = state.draft; const picker = state.players[draft.pickerIndex]; const hand = draft.hands[draft.pickerIndex].map(cardById); const picks = picker.draft.map(cardById);
    app.innerHTML = header(state.title) + `<section class="screen-head"><div class="room-code">TABLE ${state.roomCode} · DRAFT ${draft.pickRound + 1} OF 6</div><div class="eyebrow">choose one, pass the rest</div><h2>${esc(picker.name)}, choose what feels alive.</h2><p class="lead">There are no wrong picks. Take a card that makes you curious, even if it is not your whole story.</p></section>${progress(draft.pickRound, 6)}<section class="pass-card"><span><small>Pass the device to</small><br><b>${esc(picker.name)}</b></span><span class="pill"><strong>${picks.length}</strong> cards drafted</span></section><section class="card-grid">${hand.map(card => categoryCard(card, true, false)).join('')}</section>` + close();
  }
  function chooseDraft(id) {
    const draft = state.draft; const hand = draft.hands[draft.pickerIndex]; const location = hand.indexOf(id); if (location < 0) return;
    hand.splice(location, 1); state.players[draft.pickerIndex].draft.push(id);
    if (draft.pickerIndex < state.players.length - 1) draft.pickerIndex += 1;
    else { draft.pickerIndex = 0; draft.pickRound += 1; draft.hands = [draft.hands[draft.hands.length - 1], ...draft.hands.slice(0, -1)]; }
    if (draft.pickRound >= 6) { state.screen = 'draft-complete'; } save(); render();
  }
  function renderDraftComplete() {
    app.innerHTML = header(state.title) + `<section class="screen-head"><div class="eyebrow">the ingredients are in</div><h2>Each person has a small, personal deck.</h2><p class="lead">Keep your cards private until your turn. Your friends will use all six to imagine an ideal career.</p></section><section class="panel">${state.players.map(p => `<div class="pass-card"><span><b>${esc(p.name)}</b><br><small>${p.draft.length} cards drafted</small></span><span class="pill">${roundPlayers().some(roundPlayer => roundPlayer.id === p.id) ? 'spotlight round' : 'idea contributor'}</span></div>`).join('')}<div class="form-foot"><p class="helper">${roundPlayers().length} spotlight ${roundPlayers().length===1?'round is':'rounds are'} configured. We’ll start with the first selected player.</p><button class="button coral" data-action="begin-round">Open ${esc(activePlayer().name)}’s round →</button></div></section>` + close();
  }
  function beginRound() { state.round = { cards:activePlayer().draft.slice(), ideas:[], submitIndex:0, votes:{}, voteIndex:0 }; state.screen='career-prompt'; save(); render(); }
  function renderCareerPrompt() { const r = round(); const p = activePlayer(); const cards = r.cards.map(cardById); app.innerHTML = header(state.title) + `<section class="screen-head"><div class="eyebrow">${esc(p.name)}’s turn</div><h2>What could their ideal career be?</h2><p class="lead">Friends: use as many of these ingredients as you can. Think broadly—work can be a job, a practice, or something entirely new.</p></section><section class="pass-card"><span><small>Pass the device to</small><br><b>${esc(p.name)}</b></span><small>These are the full cards your friends will build from.</small></section><section class="card-grid">${cards.map(card => categoryCard(card, false, false)).join('')}</section><div class="actions" style="justify-content:center"><button class="button coral" data-action="start-submissions">Invite ideal-career ideas →</button></div>` + close(); }
  function submitters() { return state.players.filter(p => p.id !== activePlayer().id); }
  function renderSubmission() { const r = round(); const writer = submitters()[r.submitIndex]; app.innerHTML = header(state.title) + `<section class="screen-head"><div class="eyebrow">an ideal career for ${esc(activePlayer().name)}</div><h2>${esc(writer.name)}, add your idea.</h2><p class="lead">Use as many of the ingredients as you can. Go practical, go strange, or go both.</p></section><section class="panel"><div class="prompt-cards">${selectedPromptCards(r.cards)}</div><label class="field-label" for="idea">What could ${esc(activePlayer().name)}’s ideal career look like?</label><textarea id="idea" maxlength="700" placeholder="An ideal career could be…"></textarea><div class="form-foot"><p class="helper">This stays private until all ideas are in.</p><button class="button primary" data-action="submit-idea">Seal this idea →</button></div></section>` + close(); }
  function submitIdea() { const body = document.getElementById('idea').value.trim(); if (body.length < 12) return toast('Write a little more so the idea has room to breathe.'); const r = round(); r.ideas.push({ id:uid('idea'), authorId:submitters()[r.submitIndex].id, body, score:0, keep:false }); r.submitIndex++; if (r.submitIndex >= submitters().length) state.screen='reveal'; save(); render(); }
  function renderReveal() { const r = round(); app.innerHTML = header(state.title) + `<section class="screen-head"><div class="eyebrow">everything is in</div><h2>Here’s what your friends imagined.</h2><p class="lead">Read generously. These are ideal-career possibilities, not prescriptions.</p></section><section class="idea-grid">${r.ideas.map((idea,i)=>`<article class="idea reveal" style="animation-delay:${i*.1}s"><div class="quote">“</div><p>${esc(idea.body)}</p><footer>ideal career · anonymous for now</footer></article>`).join('')}</section><div class="actions" style="justify-content:center"><button class="button coral" data-action="start-voting">Vote on a career path →</button></div>` + close(); }
  function renderVote() { const r=round(); const voter=activePlayer(); const selected=r.votes[voter.id]; app.innerHTML = header(state.title)+`<section class="screen-head"><div class="eyebrow">your vote</div><h2>${esc(voter.name)}, which path feels most real?</h2><p class="lead">These are anonymous possibilities from your friends. Choose the one you feel most drawn to explore.</p></section><section class="pass-card"><span><small>This round belongs to</small><br><b>${esc(voter.name)}</b></span><small>You cast the only vote for your own round.</small></section><section class="idea-grid">${r.ideas.map(idea=>`<button class="vote-card ${selected===idea.id?'selected':''}" data-vote="${idea.id}"><span class="kind-label">ideal career</span><p>${esc(idea.body)}</p></button>`).join('')}</section><div class="actions" style="justify-content:center"><button class="button primary" data-action="next-voter" ${!selected?'disabled':''}>Choose this path →</button></div>`+close(); }
  function nextVoter() { const r=round(); const idea=r.ideas.find(x=>x.id===r.votes[activePlayer().id]); if(idea)idea.score++; state.screen='reflect'; save(); render(); }
  function renderReflect() { const r=round(), p=activePlayer(); app.innerHTML=header(state.title)+`<section class="screen-head"><div class="eyebrow">${esc(p.name)}’s collection</div><h2>What do you want to keep exploring?</h2><p class="lead">Keep whatever feels alive. Every other idea stays safely in your Idea bank—nothing is lost.</p></section><section class="panel reflection"><div><div class="prompt-cards">${selectedPromptCards(r.cards)}</div><div class="stack-list">${r.ideas.map(idea=>`<div class="reflect-item"><input id="keep-${idea.id}" data-keep="${idea.id}" type="checkbox" ${idea.keep?'checked':''}/><label for="keep-${idea.id}">${esc(idea.body)}<span class="score">${idea.score ? `${idea.score} ${idea.score===1?'vote':'votes'}` : 'No votes yet'}</span></label></div>`).join('')}</div></div><aside class="reflection-side"><h3>Take what fits.</h3><p>These are gentle invitations, not final answers. You get the final say.</p><p class="helper">No idea is deleted. This only makes your saved stack easier to return to later.</p><button class="button coral" data-action="save-reflection">Save my stacks →</button></aside></section>`+close(); }
  function saveReflection() { const r=round(), p=activePlayer(); r.ideas.forEach(idea=>{ idea.keep=!!document.querySelector(`[data-keep="${idea.id}"]`)?.checked; const saved={body:idea.body,score:idea.score,cards:r.cards}; (idea.keep?p.keep:p.bank).push(saved); }); state.completedRounds++; if(state.completedRounds >= roundPlayers().length) { state.screen='ending'; save(); copySummary(true); } else { state.activeIndex=state.players.findIndex(player => player.id === roundPlayers()[state.completedRounds].id); state.screen='round-ready'; save(); } render(); }
  function renderRoundReady() { const p=activePlayer(); app.innerHTML=header(state.title)+`<section class="screen-head"><div class="eyebrow">round ${state.completedRounds+1} of ${roundPlayers().length}</div><h2>Make space for ${esc(p.name)}.</h2><p class="lead">Their personal deck is waiting. Let’s see where their ingredients could lead.</p></section><section class="panel"><div class="pass-card"><span><small>Pass the device to</small><br><b>${esc(p.name)}</b></span><span class="pill">their turn</span></div><div class="form-foot"><p class="helper">Every spotlight player gets ideas generated specifically for them.</p><button class="button coral" data-action="begin-round">Open ${esc(p.name)}’s round →</button></div></section>`+close(); }
  function renderEnding() { app.innerHTML=header(state.title)+`<section class="screen-head"><div class="eyebrow">your table is complete</div><h2>Keep what feels alive.</h2><p class="lead">Your plain-text group summary has been copied to your clipboard. Save the good ones, leave the rest, and come back when a new thread starts pulling.</p></section><section class="ending-grid">${state.players.map(p=>`<article class="player-stack"><h3>${esc(p.name)}</h3><div class="eyebrow" style="margin-bottom:9px">keep exploring · ${p.keep.length}</div><div class="stack-list">${p.keep.length?p.keep.map(item=>`<div class="stack-item">${esc(item.body)}</div>`).join(''):'<p class="empty">Nothing pinned yet—every idea remains in the bank.</p>'}</div><div class="eyebrow" style="margin:20px 0 9px">idea bank · ${p.bank.length}</div><div class="stack-list">${p.bank.map(item=>`<div class="stack-item">${esc(item.body)}</div>`).join('')}</div></article>`).join('')}</section><div class="actions" style="justify-content:center"><button class="button quiet" data-action="copy-summary">Copy again</button><button class="button coral" data-action="new-game">Start a new table</button></div>`+close(); }
  function summaryText() { return `${state.title}\n\n` + state.players.map(p=>`${p.name}\nKeep exploring\n${p.keep.map(x=>`- ${x.body}`).join('\n')||'- None'}\n\nIdea bank\n${p.bank.map(x=>`- ${x.body}`).join('\n')||'- None'}`).join('\n\n'); }
  function copySummary(silent) { const text = summaryText(); const done = () => { if (!silent) toast('Plain-text summary copied.'); }; const fallback = () => { const area=document.createElement('textarea'); area.value=text; area.style.cssText='position:fixed;opacity:0'; document.body.append(area); area.select(); const copied=document.execCommand('copy'); area.remove(); if (!silent) toast(copied ? 'Plain-text summary copied.' : 'Copy isn’t available in this browser.'); }; if (navigator.clipboard?.writeText) navigator.clipboard.writeText(text).then(done).catch(fallback); else fallback(); }
  function render() { if (state.screen==='home') return renderHome(); if(state.screen==='setup')return renderSetup(); if(state.screen==='draft')return renderDraft(); if(state.screen==='draft-complete')return renderDraftComplete(); if(state.screen==='career-prompt')return renderCareerPrompt(); if(state.screen==='submission')return renderSubmission(); if(state.screen==='reveal')return renderReveal(); if(state.screen==='vote')return renderVote(); if(state.screen==='reflect')return renderReflect(); if(state.screen==='round-ready')return renderRoundReady(); if(state.screen==='ending')return renderEnding(); renderHome(); }
  app.addEventListener('click', event=>{ const node=event.target.closest('button, input'); if(!node)return; if(node.matches('.remove-player')){if(document.querySelectorAll('.player-entry').length>2)node.closest('.player-entry').remove(); return;} const action=node.dataset.action; if(action==='home'){if(state.screen!=='home')state.previousScreen=state.screen;state.screen='home';save();render();} if(action==='setup'){state={screen:'setup'};render();} if(action==='resume'){state.screen=state.previousScreen||'draft';save();render();} if(action==='add-player'){const container=document.getElementById('player-inputs'); if(container.children.length<8)container.insertAdjacentHTML('beforeend',playerInput('',container.children.length)); else toast('Eight people is plenty for one table.');} if(action==='start-game')startGame(); if(action==='start-submissions'){state.screen='submission';save();render();} if(action==='begin-round')beginRound(); if(action==='submit-idea')submitIdea(); if(action==='start-voting'){state.screen='vote';save();render();} if(action==='next-voter')nextVoter(); if(action==='save-reflection')saveReflection(); if(action==='copy-summary')copySummary(); if(action==='new-game'){localStorage.removeItem(STORAGE_KEY);state={screen:'setup'};render();} if(action==='reset-game'){if(window.confirm('Reset this game? This permanently removes the drafted cards and saved idea stacks from this browser.')){localStorage.removeItem(STORAGE_KEY);state={screen:'home'};render();}} const cardId=node.dataset.card; if(cardId && state.screen==='draft')chooseDraft(cardId); if(node.dataset.vote){round().votes[activePlayer().id]=node.dataset.vote;render();} });
  render();
}());
