(function () {
  'use strict';
  const app = document.getElementById('app');
  const categories = [
    ['love', 'What you love'],
    ['strength', 'What you are good at'],
    ['opportunity', 'What you can be paid for'],
    ['need', 'What the world needs']
  ];
  const KEY = 'ikigai-room-session-v1';
  let client, roomCode, snapshot, channel, timer, selected = {};

  const esc = value => String(value || '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const close = () => '</div>';
  const shell = note => `<div class="shell"><header class="topbar"><button class="brand" data-room-action="local-home"><span class="brand-mark">i</span>ikigai</button><div class="nav-actions"><span class="nav-note">${esc(note || 'shared room')}</span><button class="button reset-button" data-room-action="leave">Leave room</button></div></header>`;
  const say = message => { const node=document.createElement('div'); node.className='toast'; node.textContent=message; document.body.append(node); setTimeout(()=>node.remove(),2600); };
  const configFor = () => ({ mode:'quick', source:'premade', playerCount:8, itemsPerCategory:5, roundCount:1, roundCardCounts:Object.fromEntries(categories.map(([key])=>[key,1])) });
  async function setup() {
    if (client) return client;
    if (!window.supabase || !window.IKIGAI_SUPABASE) throw new Error('The room connection is unavailable.');
    client=window.supabase.createClient(window.IKIGAI_SUPABASE.url,window.IKIGAI_SUPABASE.publishableKey);
    const {data:{session}}=await client.auth.getSession();
    if (!session) { const {error}=await client.auth.signInAnonymously(); if(error) throw new Error('Enable Anonymous Sign-Ins in Supabase, then try again.'); }
    return client;
  }
  async function rpc(name,args) { await setup(); const {data,error}=await client.rpc(name,args); if(error) throw new Error(error.message); return data; }
  function persist() { localStorage.setItem(KEY,JSON.stringify({roomCode})); }
  function clear() { localStorage.removeItem(KEY); roomCode=null; snapshot=null; selected={}; if(timer)clearInterval(timer); timer=null; if(channel){client?.removeChannel(channel);channel=null;} }
  function broadcast() { channel?.send({type:'broadcast',event:'changed',payload:{}}); }
  async function refresh(quiet) {
    if(!roomCode)return;
    try { snapshot=await rpc('ikigai_room_snapshot',{p_code:roomCode}); render(); }
    catch(error) { if(!quiet)say(error.message); clear(); renderHome(); }
  }
  async function watch() {
    if(!roomCode)return;
    persist(); if(timer)clearInterval(timer); timer=setInterval(()=>refresh(true),3500);
    if(channel)client.removeChannel(channel);
    channel=client.channel(`ikigai-room-${roomCode}`).on('broadcast',{event:'changed'},()=>refresh(true)).subscribe();
    await refresh();
  }
  function renderHome() {
    clear();
    app.innerHTML=shell('a shared game for imagining work')+`<section class="hero"><div class="hero-copy"><div><div class="eyebrow">play together, from anywhere</div><h1>Make a life with your friends.</h1><p class="lead">Host a room, share its code, and let everyone write from their own phone. Friends can submit ideas at the same time; the person whose turn it is sees anonymous ideas and chooses one.</p><div class="actions"><button class="button coral" data-room-action="host">Host a room</button><button class="button quiet" data-room-action="join">Join a room</button><button class="button quiet" data-room-action="local-home">Use one device instead</button></div></div><aside class="hero-aside"><strong>2–8 friends · live room</strong>Each table round gives every person one turn: friends write ideas, then that person alone chooses their favorite.</aside></div><div class="category-strip">${categories.map(([key,label],i)=>`<div class="${key}"><span>0${i+1}</span><b>${label}</b></div>`).join('')}</div></section>`+close();
  }
  function renderHost() {
    app.innerHTML=shell('set up a shared room')+`<section class="screen-head"><div class="eyebrow">host a room</div><h2>Create a room code.</h2><p class="lead">Share it with friends, then choose the game settings together in the lobby.</p></section><section class="panel"><label class="field-label" for="room-host-name">Your name</label><input id="room-host-name" maxlength="24" placeholder="e.g. Ari" autofocus><div class="form-foot"><button class="button primary" data-room-action="create">Create room →</button></div></section>`+close();
    return;
    app.innerHTML=shell('set up a shared room')+`<section class="screen-head"><div class="eyebrow">host a room</div><h2>Invite your curious people.</h2><p class="lead">You will get a short room code to share. Everyone joins on their own phone before the activity stage opens.</p></section><section class="panel"><label class="field-label" for="room-host-name">Your name</label><input id="room-host-name" maxlength="24" placeholder="e.g. Ari" autofocus><label class="field-label" for="room-title">What should we call this gathering?</label><input id="room-title" maxlength="48" value="Career Possibilities"><label class="field-label" for="room-mode">Choose a game mode</label><select id="room-mode"><option value="deep">Deep · create your own activities</option><option value="quick" selected>Quick · draft pre-made activities</option><option value="custom">Custom · configure the game</option></select><div id="room-custom" hidden><label class="field-label" for="room-source">Activity source</label><select id="room-source"><option value="premade">Pre-made cards</option><option value="own">Self-generated activities</option></select><div class="config-grid"><label>Items per category<input id="room-items" type="number" min="1" max="8" value="5"></label><label>Table rounds<input id="room-rounds" type="number" min="1" max="24" value="1"></label></div><p class="field-label">Cards in each turn prompt</p><div class="config-grid category-counts">${categories.map(([key,label])=>`<label>${label}<input id="room-count-${key}" type="number" min="0" max="8" value="1"></label>`).join('')}</div></div><label class="field-label" for="room-player-count">Number of players</label><select id="room-player-count">${Array.from({length:7},(_,i)=>`<option value="${i+2}" ${i===2?'selected':''}>${i+2} players</option>`).join('')}</select><div class="form-foot"><p class="helper">Deep and Quick use five activities per category and one table round. Custom lets you set every count.</p><button class="button primary" data-room-action="create">Create room →</button></div></section>`+close();
  }
  function renderJoin() { app.innerHTML=shell('join a shared room')+`<section class="screen-head"><div class="eyebrow">join a room</div><h2>Enter your host’s room code.</h2><p class="lead">Use your own phone so you can write at the same time as everyone else.</p></section><section class="panel"><label class="field-label" for="join-name">Your name</label><input id="join-name" maxlength="24" placeholder="e.g. Sam" autofocus><label class="field-label" for="join-code">Room code</label><input id="join-code" maxlength="6" placeholder="ABC123" style="text-transform:uppercase"><div class="form-foot"><button class="button primary" data-room-action="enter">Join room →</button></div></section>`+close(); }
  function roomConfigText(config) { return `${config.mode==='deep'?'Deep':config.mode==='quick'?'Quick':'Custom'} · ${config.itemsPerCategory} activities in each category · ${config.roundCount} table ${config.roundCount===1?'round':'rounds'}`; }
  function renderSimpleLobby() { const r=snapshot.room, players=snapshot.players, enough=players.length>=2; app.innerHTML=shell(`ROOM ${r.code}`)+`<section class="screen-head"><div class="room-code">ROOM ${r.code}</div><div class="eyebrow">waiting room</div><h2>${esc(r.title)}</h2><p class="lead">Share this room code. The host can start after one friend joins.</p></section><section class="panel"><div class="pass-card"><span><small>Room code</small><br><b>${r.code}</b></span><button class="button quiet" data-room-action="copy-link">Copy</button></div><p class="helper">${roomConfigText(r.config)}</p><div class="stack-list">${players.map(p=>`<div class="pass-card"><span><b>${esc(p.name)}</b>${p.id===snapshot.me.id?' <small>(you)</small>':''}</span><span class="pill">ready</span></div>`).join('')}</div><div class="form-foot">${r.isHost?`<p class="helper">${enough?'Ready to start.':'Waiting for one friend to join.'}</p><button class="button coral" data-room-action="start-room" ${enough?'':'disabled'}>Open activity stage →</button>`:`<p class="helper">Waiting for the host to open the activity stage…</p>`}</div></section>`+close(); }
  function renderLobby() { const r=snapshot.room, players=snapshot.players, enough=players.length===r.config.playerCount; app.innerHTML=shell(`ROOM ${r.code}`)+`<section class="screen-head"><div class="room-code">ROOM ${r.code}</div><div class="eyebrow">waiting room</div><h2>${esc(r.title)}</h2><p class="lead">Share this room code or link. Once all ${r.config.playerCount} people are here, the host opens the activity stage.</p></section><section class="panel"><div class="pass-card"><span><small>Share this link</small><br><b id="room-link">${esc(location.href.split('?')[0])}?room=${r.code}</b></span><button class="button quiet" data-room-action="copy-link">Copy</button></div><p class="helper">${roomConfigText(r.config)}</p><div class="stack-list">${players.map(p=>`<div class="pass-card"><span><b>${esc(p.name)}</b>${p.id===snapshot.me.id?' <small>(you)</small>':''}</span><span class="pill">ready</span></div>`).join('')}</div><div class="form-foot">${r.isHost?`<p class="helper">${enough?'Everyone is here.':'Waiting for '+(r.config.playerCount-players.length)+' more.'}</p><button class="button coral" data-room-action="start-room" ${enough?'':'disabled'}>Open activity stage →</button>`:`<p class="helper">Waiting for the host to open the activity stage…</p>`}</div></section>`+close(); }
  function renderActivities() {
    const {room,me,players}=snapshot, own=room.config.source==='own'; const done=me.activitiesReady, everyone=players.every(p=>p.activitiesReady);
    if(done){
      const hostControl = room.isHost
        ? `<button class="button coral" data-room-action="begin-game" ${everyone ? '' : 'disabled'}>Begin round one →</button><p class="helper">${everyone ? 'Everyone is ready.' : 'Wait for everyone to finish.'}</p>`
        : `<p class="helper">${everyone ? 'The host can begin round one now.' : 'Waiting for the other decks…'}</p>`;
      app.innerHTML=shell(`ROOM ${room.code}`)+`<section class="screen-head"><div class="eyebrow">activity cards saved</div><h2>Nice. Your deck is ready.</h2><p class="lead">Everyone writes or drafts their own activity cards independently. You can wait here while the others finish.</p></section><section class="panel"><div class="stack-list">${players.map(p=>`<div class="pass-card"><span><b>${esc(p.name)}</b></span><span class="pill">${p.activitiesReady?'ready':'writing'}</span></div>`).join('')}</div><div class="form-foot">${hostControl}</div></section>`+close();return;}
    const count=room.config.itemsPerCategory;
    const content=own?categories.map(([key,label])=>`<div class="activity-inputs"><h3>${label}</h3>${Array.from({length:count},(_,i)=>`<label class="field-label" for="own-${key}-${i}">${label} activity ${i+1}</label><input class="room-own" id="own-${key}-${i}" data-category="${key}" data-ordinal="${i+1}" maxlength="80" placeholder="e.g. Exploring local food markets">`).join('')}</div>`).join(''):
      `<p class="helper">Choose exactly ${count} cards in each category.</p>${categories.map(([key,label])=>`<section><h3>${label} <small id="picked-${key}">0 / ${count}</small></h3><div class="card-grid room-card-grid">${(window.CARD_LIBRARY?.[key]||[]).map((title,i)=>`<button class="activity-card ${key}" data-room-card="${key}:${i}"><span class="card-dot"></span><span class="category">${label}</span><span class="title">${esc(title)}</span></button>`).join('')}</div></section>`).join('')}`;
    app.innerHTML=shell(`ROOM ${room.code}`)+`<section class="screen-head"><div class="eyebrow">stage 1 · your activity cards</div><h2>${own?'Write':'Choose'} what belongs in your life.</h2><p class="lead">${own?'Create':'Draft'} ${count} activities in each of the four Ikigai categories. Everyone can do this simultaneously.</p></section><section class="panel">${content}<div class="form-foot"><p class="helper">Your activity deck belongs to you.</p><button class="button primary" data-room-action="submit-activities">Save my activity cards →</button></div></section>`+close();
    updatePicks();
  }
  function updatePicks(){ if(!snapshot||snapshot.room.config.source!=='premade')return; categories.forEach(([key])=>{const n=(selected[key]||[]).length;const label=document.getElementById(`picked-${key}`);if(label)label.textContent=`${n} / ${snapshot.room.config.itemsPerCategory}`;document.querySelectorAll(`[data-room-card^="${key}:"]`).forEach(node=>node.classList.toggle('selected',(selected[key]||[]).includes(node.dataset.roomCard)));}); }
  function renderTurn() {
    const {room,turn}=snapshot; if(!turn)return; const isTarget=turn.isTarget, waiting=turn.status==='submitting', voting=turn.status==='voting', result=turn.status==='result';
    let body;
    if(waiting&&isTarget) body=`<section class="panel"><div class="prompt-cards">${turn.cards.map(c=>`<span class="prompt-card ${c.category}"><i></i>${esc(c.title)}</span>`).join('')}</div><h3>Your friends are writing at the same time.</h3><p class="lead">${turn.submittedCount} of ${turn.neededCount} anonymous ideas are in. You will see them only after everyone submits.</p></section>`;
    else if(waiting) body=turn.mySubmitted?`<section class="panel"><h3>Your idea is sealed.</h3><p class="lead">Waiting for the other friends to finish writing for ${esc(turn.targetName)}… (${turn.submittedCount} of ${turn.neededCount} submitted)</p></section>`:`<section class="panel"><div class="prompt-cards">${turn.cards.map(c=>`<span class="prompt-card ${c.category}"><i></i>${esc(c.title)}</span>`).join('')}</div><label class="field-label" for="room-idea">What could ${esc(turn.targetName)}’s ideal career look like?</label><textarea id="room-idea" maxlength="700" placeholder="An ideal career could be…"></textarea><div class="form-foot"><p class="helper">Your answer remains anonymous to ${esc(turn.targetName)}.</p><button class="button primary" data-room-action="submit-idea">Seal my idea →</button></div></section>`;
    else if(voting&&isTarget) body=`<section class="idea-grid">${turn.options.map(o=>`<button class="vote-card ${selected.vote===o.id?'selected':''}" data-room-vote="${o.id}"><span class="kind-label">ideal career · anonymous author</span><p>${esc(o.body)}</p></button>`).join('')}</section><div class="actions" style="justify-content:center"><button class="button coral" data-room-action="cast-vote" ${selected.vote?'':'disabled'}>Choose this path →</button></div>`;
    else if(voting) body=`<section class="panel"><h3>${esc(turn.targetName)} is choosing.</h3><p class="lead">All anonymous ideas are in. Only ${esc(turn.targetName)} can see and choose an idea for this turn.</p></section>`;
    else if(result&&isTarget) body=`<section class="panel"><div class="eyebrow">your selected path</div><h2>${esc(turn.winner)}</h2><p class="lead">Keep exploring it if it feels useful. When you continue, the next person receives a fresh turn.</p><div class="form-foot"><button class="button coral" data-room-action="complete-turn">Continue to the next person →</button></div></section>`;
    else body=`<section class="panel"><h3>${esc(turn.targetName)} is reflecting.</h3><p class="lead">They are the only person who sees which anonymous idea they chose. The next turn begins when they continue.</p></section>`;
    app.innerHTML=shell(`ROOM ${room.code}`)+`<section class="screen-head"><div class="eyebrow">table round ${turn.tableRound} of ${room.config.roundCount} · ${esc(turn.targetName)}’s turn</div><h2>${waiting&&!isTarget?`Write an idea for ${esc(turn.targetName)}.`:isTarget&&voting?'Which path feels most real?':`Make space for ${esc(turn.targetName)}.`}</h2><p class="lead">${waiting&&!isTarget?'Friends write simultaneously; '+esc(turn.targetName)+' will later choose one anonymous idea.':'One person votes per turn: the person whose activity cards created this prompt.'}</p></section>${body}`+close();
  }
  function renderComplete(){const r=snapshot.room;app.innerHTML=shell(`ROOM ${r.code}`)+`<section class="screen-head"><div class="eyebrow">your table is complete</div><h2>Keep what feels alive.</h2><p class="lead">Every player received ${r.config.roundCount} turn${r.config.roundCount===1?'':'s'} for their friends to imagine with them.</p></section><section class="panel"><p class="lead">Thanks for making a little room for possibilities.</p><div class="form-foot"><button class="button coral" data-room-action="leave">Done</button></div></section>`+close();}
  function render(){if(!snapshot)return renderHome();if(snapshot.room.status==='lobby')return renderSimpleLobby();if(snapshot.room.status==='activities')return renderActivities();if(snapshot.room.status==='playing')return renderTurn();return renderComplete();}
  async function create(){ const name=document.getElementById('room-host-name').value.trim(),title='Career Possibilities',config=configFor(); if(!name)return say('Enter your name.'); try{const data=await rpc('create_ikigai_room',{p_name:name,p_title:title,p_config:config});roomCode=data?.[0]?.code||data?.code;if(!roomCode)throw new Error('The room code was not returned.');await watch();broadcast();}catch(e){say(e.message);} }
  async function join(){const name=document.getElementById('join-name').value.trim(),code=document.getElementById('join-code').value.trim().toUpperCase();if(!name||!code)return say('Enter your name and room code.');try{await rpc('join_ikigai_room',{p_code:code,p_name:name});roomCode=code;await watch();broadcast();}catch(e){say(e.message);} }
  async function saveActivities(){const config=snapshot.room.config;let activities=[];if(config.source==='own'){activities=[...document.querySelectorAll('.room-own')].map(node=>({category:node.dataset.category,ordinal:Number(node.dataset.ordinal),title:node.value.trim()}));if(activities.some(a=>a.title.length<2))return say('Write every activity before continuing.');}else{for(const [key] of categories){const picks=selected[key]||[];if(picks.length!==config.itemsPerCategory)return say(`Choose ${config.itemsPerCategory} cards for every category.`);picks.forEach((token,i)=>activities.push({category:key,ordinal:i+1,title:window.CARD_LIBRARY[key][Number(token.split(':')[1])]}));}}try{await rpc('submit_ikigai_activities',{p_code:roomCode,p_activities:activities});broadcast();await refresh();}catch(e){say(e.message);} }
  async function act(name,args){try{await rpc(name,args);broadcast();await refresh();}catch(e){say(e.message);} }
  function localHome(){clear();window.IkigaiRoom.active=false;window.IkigaiLocalRender?.();}
  document.addEventListener('click',event=>{const node=event.target.closest('[data-room-action], [data-room-card], [data-room-vote]');if(!node)return;if(node.dataset.roomCard){const [key]=node.dataset.roomCard.split(':');const list=selected[key]||[];if(list.includes(node.dataset.roomCard))selected[key]=list.filter(x=>x!==node.dataset.roomCard);else if(list.length<snapshot.room.config.itemsPerCategory)selected[key]=[...list,node.dataset.roomCard];else return say(`Choose only ${snapshot.room.config.itemsPerCategory} in this category.`);updatePicks();return;}if(node.dataset.roomVote){selected.vote=node.dataset.roomVote;render();return;}const action=node.dataset.roomAction;if(action==='host')renderHost();if(action==='join')renderJoin();if(action==='local-home')localHome();if(action==='leave')renderHome();if(action==='create')create();if(action==='enter')join();if(action==='start-room')act('start_ikigai_room',{p_code:roomCode});if(action==='submit-activities')saveActivities();if(action==='begin-game')act('begin_ikigai_game',{p_code:roomCode});if(action==='submit-idea'){const body=document.getElementById('room-idea').value.trim();if(body.length<12)return say('Write a little more so the idea has room to breathe.');act('submit_ikigai_idea',{p_turn_id:snapshot.turn.id,p_body:body});}if(action==='cast-vote')act('cast_ikigai_vote',{p_turn_id:snapshot.turn.id,p_idea_id:selected.vote});if(action==='complete-turn'){selected.vote=null;act('complete_ikigai_turn',{p_turn_id:snapshot.turn.id});}if(action==='copy-link'){navigator.clipboard?.writeText(`${location.href.split('?')[0]}?room=${roomCode}`).then(()=>say('Room link copied.')).catch(()=>say(`Share room code ${roomCode}.`));}});
  document.addEventListener('change',event=>{if(event.target.id==='room-mode'){document.getElementById('room-custom').hidden=event.target.value!=='custom';}});
  window.IkigaiRoom={openHost:()=>{clear();renderHost();},openJoin:()=>{clear();renderJoin();},open:()=>renderHome(),resume:async code=>{roomCode=code;try{await setup();await watch();}catch(e){say(e.message);renderHome();}},code:()=>roomCode,active:false};
  const initialCode = new URLSearchParams(location.search).get('room');
  if (initialCode) window.IkigaiRoom.resume(initialCode.toUpperCase());
}());
